# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niehaus4/uiuc-lar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niehaus4/uiuc-lar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niehaus4/uiuc-lar/CMakeFiles /home/niehaus4/uiuc-lar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niehaus4/uiuc-lar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named speech

# Build rule for target.
speech: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 speech
.PHONY : speech

# fast build rule for target.
speech/fast:
	$(MAKE) -f src/speech/CMakeFiles/speech.dir/build.make src/speech/CMakeFiles/speech.dir/build
.PHONY : speech/fast

#=============================================================================
# Target rules for targets named imatlib

# Build rule for target.
imatlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imatlib
.PHONY : imatlib

# fast build rule for target.
imatlib/fast:
	$(MAKE) -f src/imatlib/CMakeFiles/imatlib.dir/build.make src/imatlib/CMakeFiles/imatlib.dir/build
.PHONY : imatlib/fast

#=============================================================================
# Target rules for targets named RMLE

# Build rule for target.
RMLE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RMLE
.PHONY : RMLE

# fast build rule for target.
RMLE/fast:
	$(MAKE) -f src/RMLE/CMakeFiles/RMLE.dir/build.make src/RMLE/CMakeFiles/RMLE.dir/build
.PHONY : RMLE/fast

#=============================================================================
# Target rules for targets named hmmRMLE

# Build rule for target.
hmmRMLE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hmmRMLE
.PHONY : hmmRMLE

# fast build rule for target.
hmmRMLE/fast:
	$(MAKE) -f src/RMLE/CMakeFiles/hmmRMLE.dir/build.make src/RMLE/CMakeFiles/hmmRMLE.dir/build
.PHONY : hmmRMLE/fast

#=============================================================================
# Target rules for targets named lexicon

# Build rule for target.
lexicon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexicon
.PHONY : lexicon

# fast build rule for target.
lexicon/fast:
	$(MAKE) -f src/lexicon/CMakeFiles/lexicon.dir/build.make src/lexicon/CMakeFiles/lexicon.dir/build
.PHONY : lexicon/fast

#=============================================================================
# Target rules for targets named bottleLogger

# Build rule for target.
bottleLogger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bottleLogger
.PHONY : bottleLogger

# fast build rule for target.
bottleLogger/fast:
	$(MAKE) -f src/robotools/CMakeFiles/bottleLogger.dir/build.make src/robotools/CMakeFiles/bottleLogger.dir/build
.PHONY : bottleLogger/fast

#=============================================================================
# Target rules for targets named dataPumper

# Build rule for target.
dataPumper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dataPumper
.PHONY : dataPumper

# fast build rule for target.
dataPumper/fast:
	$(MAKE) -f src/robotools/CMakeFiles/dataPumper.dir/build.make src/robotools/CMakeFiles/dataPumper.dir/build
.PHONY : dataPumper/fast

#=============================================================================
# Target rules for targets named floatToRgb

# Build rule for target.
floatToRgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 floatToRgb
.PHONY : floatToRgb

# fast build rule for target.
floatToRgb/fast:
	$(MAKE) -f src/robotools/CMakeFiles/floatToRgb.dir/build.make src/robotools/CMakeFiles/floatToRgb.dir/build
.PHONY : floatToRgb/fast

#=============================================================================
# Target rules for targets named performAction

# Build rule for target.
performAction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 performAction
.PHONY : performAction

# fast build rule for target.
performAction/fast:
	$(MAKE) -f src/robotools/CMakeFiles/performAction.dir/build.make src/robotools/CMakeFiles/performAction.dir/build
.PHONY : performAction/fast

#=============================================================================
# Target rules for targets named portToScreen

# Build rule for target.
portToScreen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 portToScreen
.PHONY : portToScreen

# fast build rule for target.
portToScreen/fast:
	$(MAKE) -f src/robotools/CMakeFiles/portToScreen.dir/build.make src/robotools/CMakeFiles/portToScreen.dir/build
.PHONY : portToScreen/fast

#=============================================================================
# Target rules for targets named armFwdKin

# Build rule for target.
armFwdKin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 armFwdKin
.PHONY : armFwdKin

# fast build rule for target.
armFwdKin/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/armFwdKin.dir/build.make src/boh11demo/CMakeFiles/armFwdKin.dir/build
.PHONY : armFwdKin/fast

#=============================================================================
# Target rules for targets named associativeMemory

# Build rule for target.
associativeMemory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 associativeMemory
.PHONY : associativeMemory

# fast build rule for target.
associativeMemory/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/associativeMemory.dir/build.make src/boh11demo/CMakeFiles/associativeMemory.dir/build
.PHONY : associativeMemory/fast

#=============================================================================
# Target rules for targets named demoGate

# Build rule for target.
demoGate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demoGate
.PHONY : demoGate

# fast build rule for target.
demoGate/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/demoGate.dir/build.make src/boh11demo/CMakeFiles/demoGate.dir/build
.PHONY : demoGate/fast

#=============================================================================
# Target rules for targets named lexiconLearner

# Build rule for target.
lexiconLearner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexiconLearner
.PHONY : lexiconLearner

# fast build rule for target.
lexiconLearner/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/lexiconLearner.dir/build.make src/boh11demo/CMakeFiles/lexiconLearner.dir/build
.PHONY : lexiconLearner/fast

#=============================================================================
# Target rules for targets named maDetect

# Build rule for target.
maDetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maDetect
.PHONY : maDetect

# fast build rule for target.
maDetect/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/maDetect.dir/build.make src/boh11demo/CMakeFiles/maDetect.dir/build
.PHONY : maDetect/fast

#=============================================================================
# Target rules for targets named phoneticClassifier

# Build rule for target.
phoneticClassifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phoneticClassifier
.PHONY : phoneticClassifier

# fast build rule for target.
phoneticClassifier/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/phoneticClassifier.dir/build.make src/boh11demo/CMakeFiles/phoneticClassifier.dir/build
.PHONY : phoneticClassifier/fast

#=============================================================================
# Target rules for targets named vaDetect

# Build rule for target.
vaDetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vaDetect
.PHONY : vaDetect

# fast build rule for target.
vaDetect/fast:
	$(MAKE) -f src/boh11demo/CMakeFiles/vaDetect.dir/build.make src/boh11demo/CMakeFiles/vaDetect.dir/build
.PHONY : vaDetect/fast

#=============================================================================
# Target rules for targets named fwdConv

# Build rule for target.
fwdConv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fwdConv
.PHONY : fwdConv

# fast build rule for target.
fwdConv/fast:
	$(MAKE) -f src/randExpDemo/CMakeFiles/fwdConv.dir/build.make src/randExpDemo/CMakeFiles/fwdConv.dir/build
.PHONY : fwdConv/fast

#=============================================================================
# Target rules for targets named randArmExplore

# Build rule for target.
randArmExplore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randArmExplore
.PHONY : randArmExplore

# fast build rule for target.
randArmExplore/fast:
	$(MAKE) -f src/randExpDemo/CMakeFiles/randArmExplore.dir/build.make src/randExpDemo/CMakeFiles/randArmExplore.dir/build
.PHONY : randArmExplore/fast

#=============================================================================
# Target rules for targets named randHead

# Build rule for target.
randHead: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randHead
.PHONY : randHead

# fast build rule for target.
randHead/fast:
	$(MAKE) -f src/randExpDemo/CMakeFiles/randHead.dir/build.make src/randExpDemo/CMakeFiles/randHead.dir/build
.PHONY : randHead/fast

#=============================================================================
# Target rules for targets named RBFMap

# Build rule for target.
RBFMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RBFMap
.PHONY : RBFMap

# fast build rule for target.
RBFMap/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/RBFMap.dir/build.make src/vision/jointAttention/CMakeFiles/RBFMap.dir/build
.PHONY : RBFMap/fast

#=============================================================================
# Target rules for targets named csSalience

# Build rule for target.
csSalience: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csSalience
.PHONY : csSalience

# fast build rule for target.
csSalience/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/csSalience.dir/build.make src/vision/jointAttention/CMakeFiles/csSalience.dir/build
.PHONY : csSalience/fast

#=============================================================================
# Target rules for targets named faceDetector

# Build rule for target.
faceDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faceDetector
.PHONY : faceDetector

# fast build rule for target.
faceDetector/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/faceDetector.dir/build.make src/vision/jointAttention/CMakeFiles/faceDetector.dir/build
.PHONY : faceDetector/fast

#=============================================================================
# Target rules for targets named gazeEstimator2

# Build rule for target.
gazeEstimator2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gazeEstimator2
.PHONY : gazeEstimator2

# fast build rule for target.
gazeEstimator2/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/gazeEstimator2.dir/build.make src/vision/jointAttention/CMakeFiles/gazeEstimator2.dir/build
.PHONY : gazeEstimator2/fast

#=============================================================================
# Target rules for targets named jointAttention

# Build rule for target.
jointAttention: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jointAttention
.PHONY : jointAttention

# fast build rule for target.
jointAttention/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/jointAttention.dir/build.make src/vision/jointAttention/CMakeFiles/jointAttention.dir/build
.PHONY : jointAttention/fast

#=============================================================================
# Target rules for targets named jointAttention3d

# Build rule for target.
jointAttention3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jointAttention3d
.PHONY : jointAttention3d

# fast build rule for target.
jointAttention3d/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/jointAttention3d.dir/build.make src/vision/jointAttention/CMakeFiles/jointAttention3d.dir/build
.PHONY : jointAttention3d/fast

#=============================================================================
# Target rules for targets named objSegTrack

# Build rule for target.
objSegTrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objSegTrack
.PHONY : objSegTrack

# fast build rule for target.
objSegTrack/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/objSegTrack.dir/build.make src/vision/jointAttention/CMakeFiles/objSegTrack.dir/build
.PHONY : objSegTrack/fast

#=============================================================================
# Target rules for targets named objectFeatures

# Build rule for target.
objectFeatures: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectFeatures
.PHONY : objectFeatures

# fast build rule for target.
objectFeatures/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/objectFeatures.dir/build.make src/vision/jointAttention/CMakeFiles/objectFeatures.dir/build
.PHONY : objectFeatures/fast

#=============================================================================
# Target rules for targets named objectSalience

# Build rule for target.
objectSalience: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectSalience
.PHONY : objectSalience

# fast build rule for target.
objectSalience/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/objectSalience.dir/build.make src/vision/jointAttention/CMakeFiles/objectSalience.dir/build
.PHONY : objectSalience/fast

#=============================================================================
# Target rules for targets named objectSegmentation

# Build rule for target.
objectSegmentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectSegmentation
.PHONY : objectSegmentation

# fast build rule for target.
objectSegmentation/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/objectSegmentation.dir/build.make src/vision/jointAttention/CMakeFiles/objectSegmentation.dir/build
.PHONY : objectSegmentation/fast

#=============================================================================
# Target rules for targets named randObjSeg

# Build rule for target.
randObjSeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 randObjSeg
.PHONY : randObjSeg

# fast build rule for target.
randObjSeg/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/randObjSeg.dir/build.make src/vision/jointAttention/CMakeFiles/randObjSeg.dir/build
.PHONY : randObjSeg/fast

#=============================================================================
# Target rules for targets named shakeSalience

# Build rule for target.
shakeSalience: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shakeSalience
.PHONY : shakeSalience

# fast build rule for target.
shakeSalience/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/shakeSalience.dir/build.make src/vision/jointAttention/CMakeFiles/shakeSalience.dir/build
.PHONY : shakeSalience/fast

#=============================================================================
# Target rules for targets named topDownObjectMap

# Build rule for target.
topDownObjectMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 topDownObjectMap
.PHONY : topDownObjectMap

# fast build rule for target.
topDownObjectMap/fast:
	$(MAKE) -f src/vision/jointAttention/CMakeFiles/topDownObjectMap.dir/build.make src/vision/jointAttention/CMakeFiles/topDownObjectMap.dir/build
.PHONY : topDownObjectMap/fast

#=============================================================================
# Target rules for targets named stereoBallLoc

# Build rule for target.
stereoBallLoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoBallLoc
.PHONY : stereoBallLoc

# fast build rule for target.
stereoBallLoc/fast:
	$(MAKE) -f src/vision/blobTracker3d/CMakeFiles/stereoBallLoc.dir/build.make src/vision/blobTracker3d/CMakeFiles/stereoBallLoc.dir/build
.PHONY : stereoBallLoc/fast

#=============================================================================
# Target rules for targets named stereoBlobTrack

# Build rule for target.
stereoBlobTrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoBlobTrack
.PHONY : stereoBlobTrack

# fast build rule for target.
stereoBlobTrack/fast:
	$(MAKE) -f src/vision/blobTracker3d/CMakeFiles/stereoBlobTrack.dir/build.make src/vision/blobTracker3d/CMakeFiles/stereoBlobTrack.dir/build
.PHONY : stereoBlobTrack/fast

#=============================================================================
# Target rules for targets named depthMap

# Build rule for target.
depthMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 depthMap
.PHONY : depthMap

# fast build rule for target.
depthMap/fast:
	$(MAKE) -f src/vision/stereoAttention/CMakeFiles/depthMap.dir/build.make src/vision/stereoAttention/CMakeFiles/depthMap.dir/build
.PHONY : depthMap/fast

#=============================================================================
# Target rules for targets named egoRemapper

# Build rule for target.
egoRemapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 egoRemapper
.PHONY : egoRemapper

# fast build rule for target.
egoRemapper/fast:
	$(MAKE) -f src/vision/stereoAttention/CMakeFiles/egoRemapper.dir/build.make src/vision/stereoAttention/CMakeFiles/egoRemapper.dir/build
.PHONY : egoRemapper/fast

#=============================================================================
# Target rules for targets named stereoAttention

# Build rule for target.
stereoAttention: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoAttention
.PHONY : stereoAttention

# fast build rule for target.
stereoAttention/fast:
	$(MAKE) -f src/vision/stereoAttention/CMakeFiles/stereoAttention.dir/build.make src/vision/stereoAttention/CMakeFiles/stereoAttention.dir/build
.PHONY : stereoAttention/fast

#=============================================================================
# Target rules for targets named stereoIOR

# Build rule for target.
stereoIOR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoIOR
.PHONY : stereoIOR

# fast build rule for target.
stereoIOR/fast:
	$(MAKE) -f src/vision/stereoAttention/CMakeFiles/stereoIOR.dir/build.make src/vision/stereoAttention/CMakeFiles/stereoIOR.dir/build
.PHONY : stereoIOR/fast

#=============================================================================
# Target rules for targets named stereoVision

# Build rule for target.
stereoVision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoVision
.PHONY : stereoVision

# fast build rule for target.
stereoVision/fast:
	$(MAKE) -f src/vision/stereoVision/CMakeFiles/stereoVision.dir/build.make src/vision/stereoVision/CMakeFiles/stereoVision.dir/build
.PHONY : stereoVision/fast

#=============================================================================
# Target rules for targets named balanceDemo

# Build rule for target.
balanceDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 balanceDemo
.PHONY : balanceDemo

# fast build rule for target.
balanceDemo/fast:
	$(MAKE) -f src/balancing/PIDBeam/CMakeFiles/balanceDemo.dir/build.make src/balancing/PIDBeam/CMakeFiles/balanceDemo.dir/build
.PHONY : balanceDemo/fast

#=============================================================================
# Target rules for targets named stereoCalib

# Build rule for target.
stereoCalib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereoCalib
.PHONY : stereoCalib

# fast build rule for target.
stereoCalib/fast:
	$(MAKE) -f src/graspDemo/CMakeFiles/stereoCalib.dir/build.make src/graspDemo/CMakeFiles/stereoCalib.dir/build
.PHONY : stereoCalib/fast

#=============================================================================
# Target rules for targets named objectMover

# Build rule for target.
objectMover: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectMover
.PHONY : objectMover

# fast build rule for target.
objectMover/fast:
	$(MAKE) -f src/interactiondemo/CMakeFiles/objectMover.dir/build.make src/interactiondemo/CMakeFiles/objectMover.dir/build
.PHONY : objectMover/fast

#=============================================================================
# Target rules for targets named objectMoverART

# Build rule for target.
objectMoverART: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectMoverART
.PHONY : objectMoverART

# fast build rule for target.
objectMoverART/fast:
	$(MAKE) -f src/interactiondemo/CMakeFiles/objectMoverART.dir/build.make src/interactiondemo/CMakeFiles/objectMoverART.dir/build
.PHONY : objectMoverART/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... speech"
	@echo "... imatlib"
	@echo "... RMLE"
	@echo "... hmmRMLE"
	@echo "... lexicon"
	@echo "... bottleLogger"
	@echo "... dataPumper"
	@echo "... floatToRgb"
	@echo "... performAction"
	@echo "... portToScreen"
	@echo "... armFwdKin"
	@echo "... associativeMemory"
	@echo "... demoGate"
	@echo "... lexiconLearner"
	@echo "... maDetect"
	@echo "... phoneticClassifier"
	@echo "... vaDetect"
	@echo "... fwdConv"
	@echo "... randArmExplore"
	@echo "... randHead"
	@echo "... RBFMap"
	@echo "... csSalience"
	@echo "... faceDetector"
	@echo "... gazeEstimator2"
	@echo "... jointAttention"
	@echo "... jointAttention3d"
	@echo "... objSegTrack"
	@echo "... objectFeatures"
	@echo "... objectSalience"
	@echo "... objectSegmentation"
	@echo "... randObjSeg"
	@echo "... shakeSalience"
	@echo "... topDownObjectMap"
	@echo "... stereoBallLoc"
	@echo "... stereoBlobTrack"
	@echo "... depthMap"
	@echo "... egoRemapper"
	@echo "... stereoAttention"
	@echo "... stereoIOR"
	@echo "... stereoVision"
	@echo "... balanceDemo"
	@echo "... stereoCalib"
	@echo "... objectMover"
	@echo "... objectMoverART"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

