yarp connect /icubSim/cam/left /sall/view
yarp connect /icubSim/cam/right /salr/view
yarp connect /egoRemapper/agg:l /ftl/img:i
yarp connect /ftl/img:o /leftcam
yarp connect /egoRemapper/agg:r /ftr/img:i
yarp connect /ftr/img:o /rightcam
yarp connect /icubSim/head/state:o /egoRemapper/pos:h
yarp connect /sall/map /egoRemapper/map0:l
yarp connect /salr/map /egoRemapper/map0:r
